[linux_x86_64]
location = "~/.local/bin"
packages = [
  { name = "curl", url = "https://github.com/moparisthebest/static-curl/releases/download/v8.7.1/curl-amd64" },
  { bin = "fzf", name = "fzf", archive = "https://github.com/junegunn/fzf/releases/download/v0.55.0/fzf-0.55.0-linux_amd64.tar.gz" },
  { bin = "ripgrep-14.1.0-x86_64-unknown-linux-musl/rg", name = "rg", archive = "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz" },
  { bin = "fd-v10.2.0-x86_64-unknown-linux-musl/fd", name = "fd", archive = "https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz" },
  { bin = "yazi-x86_64-unknown-linux-musl/yazi", name = "yazi", archive = "https://github.com/sxyazi/yazi/releases/download/v0.3.3/yazi-x86_64-unknown-linux-musl.zip" },
  { bin = "starship", name = "starship", archive = "https://github.com/starship/starship/releases/download/v1.20.1/starship-x86_64-unknown-linux-musl.tar.gz" },
  { name = "nvim", url = "https://github.com/neovim/neovim-releases/releases/download/v0.10.1/nvim.appimage" },
  { name = "tmux", url = "https://github.com/nelsonenzo/tmux-appimage/releases/download/3.3a/tmux.appimage" },
  { bin = "fnm", name = "fnm", archive = "https://github.com/Schniz/fnm/releases/download/v1.37.1/fnm-linux.zip" },
  { bin = "eza", name = "eza", archive = "https://github.com/eza-community/eza/releases/download/v0.19.2/eza_x86_64-unknown-linux-musl.tar.gz" },
  { bin = "stew", name = "stew", archive = "https://github.com/marwanhawari/stew/releases/download/v0.4.0/stew-v0.4.0-linux-amd64.tar.gz" },
  { bin = "zoxide", name = "z", archive = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.6/zoxide-0.9.6-x86_64-unknown-linux-musl.tar.gz" },
  { bin = "termchat-v1.3.1-x86_64-unknown-linux-musl/termchat", name = "termchat", archive = "https://github.com/lemunozm/termchat/releases/download/v1.3.1/termchat-v1.3.1-x86_64-unknown-linux-musl.tar.gz" },
]
