return {
	-- {
	-- 	"zbirenbaum/copilot.lua",
	-- 	cmd = "Copilot",
	-- 	event = "InsertEnter",
	-- 	dependencies = {
	-- 		{ "nvim-lua/plenary.nvim" },
	-- 		{ "folke/which-key.nvim" },
	-- 	},
	-- 	config = function()
	-- 		require("which-key").add({ { "<leader>c", group = "Copilot" } })
	-- 		require("copilot").setup({
	-- 			panel = {
	-- 				enabled = true,
	-- 				auto_refresh = false,
	-- 				keymap = {
	-- 					jump_prev = "[[",
	-- 					jump_next = "]]",
	-- 					accept = "<CR>",
	-- 					refresh = "gr",
	-- 					open = "<M-CR>",
	-- 				},
	-- 				layout = {
	-- 					position = "bottom", -- | top | left | right
	-- 					ratio = 0.4,
	-- 				},
	-- 			},
	-- 			suggestion = {
	-- 				enabled = true,
	-- 				auto_trigger = true,
	-- 				debounce = 75,
	-- 				keymap = {
	-- 					accept = "<C-j>",
	-- 					accept_line = "<M-j>",
	-- 					next = "<M-]>",
	-- 					prev = "<M-[>",
	-- 					dismiss = "<C-]>",
	-- 				},
	-- 			},
	-- 			filetypes = {
	-- 				yaml = true,
	-- 				markdown = true,
	-- 				help = false,
	-- 				gitcommit = false,
	-- 				gitrebase = false,
	-- 				hgcommit = false,
	-- 				svn = false,
	-- 				cvs = false,
	-- 				["."] = false,
	-- 			},
	-- 			copilot_node_command = "node", -- Node.js version must be > 18.x
	-- 			server_opts_overrides = {},
	-- 		})
	-- 	end,
	-- },
	-- {
	-- 	"CopilotC-Nvim/CopilotChat.nvim",
	-- 	branch = "main",
	-- 	dependencies = {
	-- 		{ "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
	-- 		{ "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
	-- 	},
	-- 	build = "make tiktoken",
	-- 	opts = {
	-- 		chat_autocomplete = false,
	-- 		window = {
	-- 			layout = "vertical", -- 'vertical', 'horizontal', 'float', 'replace'
	-- 			-- width = 0.75, -- fractional width of parent, or absolute width in columns when > 1
	-- 			-- height = 0.75, -- fractional height of parent, or absolute height in rows when > 1
	-- 		},
	-- 		mappings = {
	-- 			complete = {
	-- 				insert = "<Tab>",
	-- 			},
	-- 		},
	-- 		prompts = {
	-- 			Gramatika = {
	-- 				prompt = ">$gpt-4o\n\nPrepis text so Slovenskou diakritikou, gramaticke chyby, ciarky a slovosled smies upravit, no slova alebo vyznam viet nemen.",
	-- 				system_prompt = "You are thorough and precise when getting your task done. You will do exactly what user wants you to. You will be tasked to help with text, do not write line numbers",
	-- 				mapping = "<leader>csk",
	-- 				description = "Will rewrite slovak text with correct grammar",
	-- 			},
	-- 			Grammar = {
	-- 				prompt = ">$gpt-4o\n\nRewrite the text with correct English grammar, punctuation, and sentence structure. Do not change the meaning of the sentences.",
	-- 				system_prompt = "You are thorough and precise when getting your task done. You will do exactly what user wants you to. You will be tasked to help with text, do not write line numbers",
	-- 				mapping = "<leader>cen",
	-- 				description = "Will rewrite English text with correct grammar",
	-- 			},
	-- 		},
	-- 	},
	-- 	keys = {
	-- 		{ "<leader>ccs", ":CopilotChatStop<CR>", desc = "CopilotChat Stop", mode = { "n", "v" } },
	-- 		{
	-- 			"<leader>cco",
	-- 			function()
	-- 				require("CopilotChat").toggle()
	-- 			end,
	-- 			mode = { "n", "v" },
	-- 			desc = "CopilotChat - Toggle",
	-- 		},
	-- 		{
	-- 			"<leader>ccf",
	-- 			function()
	-- 				vim.cmd("normal! ggVG")
	-- 				require("CopilotChat").toggle()
	-- 			end,
	-- 		},
	-- 	},
	-- },
}
