"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ]()\
$os\
$directory\
$git_branch\
$git_status\
[|]()\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[|](fg:color_base04)\
$time\
$cmd_duration\
$status\
$line_break$character"""

palette = 'base16_ansii_theme'

[palettes.base16_ansii_theme]
color_base00 = 'black'
color_base01 = 'bright-black'
color_base02 = 'dimmed'
color_base03 = 'dimmed'
color_base04 = 'white'
color_base05 = 'bright-white'
color_base06 = 'bright-white'
color_base07 = 'bright-white'
color_base08 = 'red'
color_base09 = 'yellow'
color_base0a = 'yellow'
color_base0b = 'green'
color_base0c = 'cyan'
color_base0d = 'blue'
color_base0e = 'magenta'
color_base0f = 'red'

[os]
disabled = false
style = "fg:color_base07"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[[| $symbol $branch ](fg:color_base0a)]()'

[git_status]
format = '[[($all_status$ahead_behind )](fg:color_base0d)]()'

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base0c)]()'

[bun]
format = '[[ $symbol( $version) ](fg:color_base07)]()'

[c]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_base0d)]()'

[rust]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base09)]()'

[golang]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base0d)]()'

[php]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base0e)]()'

[java]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_base0d)]()'

[kotlin]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base0d)]()'

[haskell]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base0e)]()'

[python]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_base0d)]()'

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:color_base04)]()'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold fg:color_base0b)'
error_symbol = '[>](bold fg:color_base08)'
vimcmd_symbol = '[>](bold fg:color_base0a)'
vimcmd_replace_one_symbol = '[<](bold fg:color_base0e)'
vimcmd_replace_symbol = '[<](bold fg:color_base0e)'
vimcmd_visual_symbol = '[<](bold fg:color_base0a)'
format = '[ $symbol ]()'

[cmd_duration]
disabled = false
min_time = 500
format = '[| [$duration](fg:color_base04) ]()'

[status]
disabled = false
symbol = ''
format = '[| $symbol$status]($style) '
